import { GenAIArtViewed } from "../../contexts/GenAIArtContext";

export const content: Record<string, any> = {
  [GenAIArtViewed.HyperSpaceFlux1]: {
    artOption: GenAIArtViewed.HyperSpaceFlux1,
    filePath: "hyperspace-flux-1",
    ext: ".jpeg",
    prompt: "hyperspace flux colourful vibrant neon abstract background ",
    ai: "Meta AI Imagine",
    link: "https://imagine.meta.com/",
    len: 4,
  },
  [GenAIArtViewed.BioCity1]: {
    artOption: GenAIArtViewed.BioCity1,
    filePath: "bio-city-1",
    ext: ".png",
    prompt:
      "Illustrate a bustling metropolis at dusk, where advanced futuristic skyscrapers seamlessly blend with organic, bioluminescent structures, creating a harmonious cityscape that reflects the perfect integration of nature and technology",
    negativePrompt: "Blurs, low quality elements, pixelation",
    styles: "'Fooocus Masterpiece', 'Fooocus Sharp', 'MRE Anime', 'SAI Anime'",
    baseModel: "juggernautXL_version6Rundiffusion.safetensors",
    sampler: "dpmpp_2m_sde_gpu",
    lora1: "sd_xl_offset_example-lora_1.0.safetensors : 0.1",
    ai: "Fooocus",
    link: "https://github.com/lllyasviel/Fooocus",
    len: 4,
  },
  [GenAIArtViewed.AnimePowerarmourGuy1]: {
    artOption: GenAIArtViewed.AnimePowerarmourGuy1,
    filePath: "anime-powerarmour-guy-1",
    ext: ".png",
    prompt:
      "handsome man with short black hair and light blue eyes wearing navy blue and gold power armour, detailed, cinematic, complex, highly coherent, elegant, intricate, sharp focus, dramatic, dynamic, illuminated background, professional, artistic, new, inspiring, attractive, creative, adventurous, inspired, beautiful, confident, pretty, lucky, passionate, unique, cool, awesome, amazing",
    styles: "'Fooocus V2', 'MRE Anime', 'SAI Anime', 'MRE Manga', 'Misc Manga'",
    baseModel: "juggernautXL_version6Rundiffusion.safetensors",
    sampler: "dpmpp_2m_sde_gpu",
    lora1: "sd_xl_offset_example-lora_1.0.safetensors : 0.1",
    ai: "Fooocus",
    link: "https://github.com/lllyasviel/Fooocus",
    len: 6,
  },
  [GenAIArtViewed.AnimePowerarmourGuy2]: {
    artOption: GenAIArtViewed.AnimePowerarmourGuy2,
    filePath: "anime-powerarmour-guy-2",
    ext: ".png",
    prompt:
      "Handsome young man with orange eyes and black hair with no helmet wearing cybertronic Sauron-inspired power armour, detailed, intricate, elegant, highly extended, extremely stylish, holy light, glowing atmosphere, sharp focus, perfect composition, dramatic, dynamic background, fine detail, full color, inspired, marvelous, amazing, creative, calm, cute, vibrant, illuminated",
    styles:
      "'Fooocus V2', 'Fooocus Enhance', 'Fooocus Sharp', 'MRE Manga', 'MRE Anime', 'Futuristic Cybernetic', 'Futuristic Futuristic', 'Futuristic Cybernetic Robot'",
    baseModel: "juggernautXL_version6Rundiffusion.safetensors",
    sampler: "dpmpp_2m_sde_gpu",
    lora1: "sd_xl_offset_example-lora_1.0.safetensors : 0.1",
    ai: "Fooocus",
    link: "https://github.com/lllyasviel/Fooocus",
    len: 4,
  },
  [GenAIArtViewed.AnimePowerarmourGuy3]: {
    artOption: GenAIArtViewed.AnimePowerarmourGuy3,
    filePath: "anime-powerarmour-guy-3",
    ext: ".png",
    prompt:
      "Full body image of a handsome man with maroon hair and demonic orange eyes without a helmet wearing power armour in the style of Sauron from Lord of the Rings and generic Cyberpunk, dramatic cinematic light, detailed, relaxed, full, sharp focus, extremely fine detail, intricate, elegant, rich deep colors, perfect, symmetry, highly saturated, innocent, scientific, color",
    styles: "'Fooocus V2', 'MRE Anime', 'MRE Manga', 'SAI Anime'",
    baseModel: "juggernautXL_version6Rundiffusion.safetensors",
    sampler: "dpmpp_2m_sde_gpu",
    lora1: "sd_xl_offset_example-lora_1.0.safetensors : 0.1",
    ai: "Fooocus",
    link: "https://github.com/lllyasviel/Fooocus",
    len: 4,
  },
  [GenAIArtViewed.AnimePrincessSamuraiGirl1]: {
    artOption: GenAIArtViewed.AnimePrincessSamuraiGirl1,
    filePath: "anime-princess-samurai-girl-1",
    ext: ".png",
    prompt:
      "stoic beautiful woman with long brunette hair and light hazel eyes wearing samurai armour made out of ruby gemstones, cinematic, stunning, highly detailed, formal, serious, determined, elegant, color, real, sharp focus, very coherent, perfect, full colorful, amazing, attractive, pretty, cute, enhanced, symmetry, intricate, elite, cool, nice",
    styles: "'Fooocus V2', 'MRE Anime', 'SAI Anime', 'MRE Manga', 'Misc Manga'",
    baseModel: "juggernautXL_version6Rundiffusion.safetensors",
    sampler: "dpmpp_2m_sde_gpu",
    lora1: "sd_xl_offset_example-lora_1.0.safetensors : 0.1",
    ai: "Fooocus",
    link: "https://github.com/lllyasviel/Fooocus",
    len: 6,
  },
  [GenAIArtViewed.DemonSamurai1]: {
    artOption: GenAIArtViewed.DemonSamurai1,
    filePath: "demon-samurai-1",
    ext: ".png",
    prompt:
      "Full body image of a demon samurai with metallic black and purple armour, covered in flags and spikes, cinematic, dynamic light, detailed, sharp focus, winning, grand, open, transparent, highly intricate, artistic, innocent, still, pretty, symmetry, great composition, perfect, aesthetic, very inspirational, real, fine detail, clear, crisp, original, creative, novel",
    styles: "'Fooocus V2', 'MRE Anime', 'SAI Anime', 'MRE Manga', 'Misc Manga'",
    baseModel: "juggernautXL_version6Rundiffusion.safetensors",
    sampler: "dpmpp_2m_sde_gpu",
    lora1: "sd_xl_offset_example-lora_1.0.safetensors : 0.1",
    ai: "Fooocus",
    link: "https://github.com/lllyasviel/Fooocus",
    len: 6,
  },
};
